"""allow nullable password and recipe user_id

Revision ID: 38af1fbe718d
Revises: 01aaea2958dc
Create Date: 2025-09-27 01:56:55.557371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38af1fbe718d'
down_revision = '01aaea2958dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
